- name: Install nginx
  yum: pkg=nginx state=latest

- name: Set nginx default config
  template: src=etc_nginx_nginx.conf.j2 dest=/etc/nginx/nginx.conf group=root owner=root force=yes

- name: Install vhost config file
  template: src=etc_nginx_app.conf.j2 dest=/etc/nginx/conf.d/{{app_name}}.conf group=root owner=root force=yes

- name: Give nginx user permissions to tmp folder
  file: path=/var/lib/nginx owner=deploy group=deploy state=directory recurse=yes

- name: Restart nginx
  action: service name=nginx state=restarted enabled=yes
